export const GET_ERRORS = "GET_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_OFF = "SET_CURRENT_USER_OFF";

export const CLEAR_CURRENT_CONTACT = "CLEAR_CURRENT_CONTACT";
export const CONTACT_LODING = "CONTACT_LODING";
export const GET_CONTACT = "GET_CONTACT";
export const GET_CONTACTS = "GET_CONTACTS";
export const CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND";